title: 'Martin Prell <br><sub><sup>Dr. phil.</sup></sub>'
description: Angaben zu Vita, Forschungsschwerpunkten und Publikationen.
lang: de

theme: jekyll-theme-cayman

url: "https://mprell.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
